name: graph_viz
channels:
  - plotly
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - backcall=0.1.0=py37_0
  - decorator=4.4.2=py_0
  - entrypoints=0.3=py37_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - joblib=0.14.1=py_0
  - jupyter_client=6.0.0=py_0
  - jupyter_core=4.6.1=py37_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - parso=0.6.2=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.6.1=py_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py37h0a44026_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - tornado=6.0.4=py37h1de35cc_1
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.8=py_0
  - zeromq=4.3.1=h0a44026_3
  - attrs=19.3.0=py_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hec6a9b0_1003
  - certifi=2019.11.28=py37hc8dfbb8_1
  - click=7.1.1=pyh8c360ce_0
  - dash=1.9.1=py_0
  - dash-core-components=1.8.1=py_0
  - dash-html-components=1.0.2=py_0
  - dash-renderer=1.2.4=py_0
  - dash-table=4.6.1=py_0
  - flask=1.1.1=py_1
  - flask-compress=1.4.0=py_0
  - fontconfig=2.13.1=h6b1039f_1001
  - future=0.18.2=py37hc8dfbb8_1
  - gettext=0.19.8.1=h46ab8bc_1002
  - glib=2.58.3=h9d45998_1002
  - gmp=6.1.2=h0a44026_1000
  - icu=64.2=h6de7cb9_1
  - igraph=0.7.1=h02d7eb0_1007
  - importlib-metadata=1.5.0=py37hc8dfbb8_1
  - importlib_metadata=1.5.0=1
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - libiconv=1.15=h01d97ff_1005
  - libxml2=2.9.10=h53d96d6_0
  - markupsafe=1.1.1=py37h9bfed18_1
  - nbformat=5.0.4=py_0
  - openssl=1.1.1e=h0b31af3_0
  - pcre=8.41=h0a44026_1003
  - pixman=0.38.0=h01d97ff_1003
  - pycairo=1.19.1=py37h4e38901_1
  - pyrsistent=0.15.7=py37h9bfed18_1
  - python-igraph=0.7.1.post7=py37h0b31af3_0
  - python_abi=3.7=1_cp37m
  - pyyaml=5.3.1=py37h9bfed18_0
  - werkzeug=1.0.0=py_0
  - yaml=0.2.2=h0b31af3_1
  - zipp=3.1.0=py_0
  - asn1crypto=1.3.0=py37_0
  - blas=1.0=mkl
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37ha12b0ac_0
  - freetype=2.9.1=hb4e5f40_0
  - idna=2.9=py_1
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.2=h0a44026_0
  - ninja=1.9.0=py37h04f5b5a_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - olefile=0.46=py_0
  - pandas=1.0.3=py37h6c726b0_0
  - pillow=7.0.0=py37h4655f20_0
  - pip=20.0.2=py37_1
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_2
  - pytz=2019.3=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.23.0=py37_0
  - retrying=1.3.3=py_2
  - setuptools=46.0.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.25.8=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - chart-studio=1.0.0=py_0
  - plotly=4.5.4=py_0
  - pytorch=1.4.0=py3.7_0
  - torchvision=0.5.0=py37_cpu
  - pip:
    - torch==1.4.0
prefix: /Users/christopherhamblin/anaconda3/envs/graph_viz

